//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichCoPhieu
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayGaiDich { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> IDLenh { get; set; }
        public Nullable<int> IDNguoiMua { get; set; }
    
        public virtual LenhGiaoDich LenhGiaoDich { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
