//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDIchVang
    {
        public int ID { get; set; }
        public string TenGiaoDich { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<int> IDVang { get; set; }
        public Nullable<bool> TinhTrangGiaoDich { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Vang Vang { get; set; }
    }
}
