//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LenhGiaoDich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LenhGiaoDich()
        {
            this.GiaoDichCoPhieu = new HashSet<GiaoDichCoPhieu>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Giá")]
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        [Display(Name = "Số cổ phiếu")]
        public Nullable<int> TongSoCoPhieu { get; set; }
        public Nullable<bool> KetQua { get; set; }


        [Display(Name = "Mua/Bán")]
        public string TheLoai { get; set; }

        [Display(Name = "Tên loại cổ phiếu")]
        public string TenCoPhieu { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IdCoPhieu { get; set; }
        public virtual CoPhieu CoPhieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichCoPhieu> GiaoDichCoPhieu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
