//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UngDungGiaoDichEntities9 : DbContext
    {
        public UngDungGiaoDichEntities9()
            : base("name=UngDungGiaoDichEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoPhieu> CoPhieu { get; set; }
        public virtual DbSet<GiaoDichCoPhieu> GiaoDichCoPhieu { get; set; }
        public virtual DbSet<GiaoDIchVang> GiaoDIchVang { get; set; }
        public virtual DbSet<HinhAnhNhaDat> HinhAnhNhaDat { get; set; }
        public virtual DbSet<LenhGiaoDich> LenhGiaoDich { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<NhaDat> NhaDat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiemVang> TiemVang { get; set; }
        public virtual DbSet<TheLoai> TheLoai { get; set; }
        public virtual DbSet<User_CoPhieu> User_CoPhieu { get; set; }
        public virtual DbSet<Vang> Vang { get; set; }
    }
}
