//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaDat()
        {
            this.HinhAnhNhaDat = new HashSet<HinhAnhNhaDat>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LoaiNhaDat { get; set; }
        public Nullable<int> IDChuSoHuu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhNhaDat> HinhAnhNhaDat { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
