//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string IDTK { get; set; }
        public string TenTk { get; set; }
        public string Password { get; set; }
        public string IDKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
        public virtual TaiKhoan TaiKhoan2 { get; set; }
    }
}
