//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UngDungGiaoDich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CoPhieu
    {
        public int ID { get; set; }
        public Nullable<int> IDChuSoHuu { get; set; }
        public Nullable<int> IDCoPhieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual CoPhieu CoPhieu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
